### ISSUE TITLE
Trackker didn't start

### ISSUE THREAD

**Issue by sundarpatan** [LordHansCapon/cotw-harvest-tracker#17]
- CotW Harvest Tracker v1.18 -
Searching for theHunterCotW_F process...
Base address: 0x7ff72ff50000
Traceback (most recent call last):
  File "\cotw-harvest-tracker-1.18\src\cotw-harvest-tracker\main.py", line 80, in <module>
    fur_type_detour_address += 54
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'

**Comment by garywilson4** [comment]
I'm getting this am i doing something wrong?
 
- CotW Harvest Tracker v1.18 -
Searching for theHunterCotW_F process...
Base address: 0x7ff7c0830000
Traceback (most recent call last):
  File "main.py", line 80, in <module>
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'
[10076] Failed to execute script 'main' due to unhandled exception!

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.

**Comment by LordHansCapon** [comment]
The game has been updated and the 1.18 tracker version is outdated. A new 2.0 version of the software is on experimental branch. A future release will resolve the compatibility issue.
